#      __  __              _               
#     / / / /__  ________ ( )_____         
#    / /_/ / _ \/ ___/ _ \|// ___/          
#   / __  /  __/ /  /  __/ (__  )           
#  /_/ /_/\___/_/   \___/ /____/            
#        __      __                      __ 
#       / /___  / /_  ____  ____  __  __/ / 
#  __  / / __ \/ __ \/ __ \/ __ \/ / / / /  
# / /_/ / /_/ / / / / / / / / / / /_/ /_/   
# \____/\____/_/ /_/_/ /_/_/ /_/\__, (_)    
#                              /____/      

### Variables ###

# Use Mod1|2|3|4|5 -> Alt|Num Lock|custom|Logo Key|AltGr
# Replace by Super the same key 
# set $mod Mod4

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

# Your preferred terminal emulator
set $term wezterm

# Your preferred application launcher
set $menu wofi --show drun

# I use this just to see what happened and failed 
# --conf=$HOME/.config/wofi/config --style=$HOME/.config/wofi/style.css > $HOME/wofi_error.log 2>&1

# Here you can set and change your theme and cursor
# it reads the settings left by nwg-look
set $font_name "$(grep 'gtk-font-name' ~/.config/gtk-3.0/settings.ini | cut -d '=' -f2)"
set $icon_theme "$(grep 'gtk-icon-theme-name' ~/.config/gtk-3.0/settings.ini | cut -d'=' -f2)"
set $cursor_theme "$(grep 'gtk-cursor-theme-name' ~/.config/gtk-3.0/settings.ini | cut -d'=' -f2)"
set $cursor_size "$(grep 'gtk-cursor-theme-size' ~/.config/gtk-3.0/settings.ini | cut -d '=' -f2)"

# Here you can set and change you monitors config
# it reads the file generate by nwg-display
set $output "$(cat ~/.config/sway/outputs)"
