#       _                  _                                        _
#      | | __ _ _ ____   _(_)___   _ __ _   _ _ __    ___ _   _  __| | ___
#   _  | |/ _` | '__\ \ / / / __| | '__| | | | '_ \  / __| | | |/ _` |/ _ \
#  | |_| | (_| | |   \ V /| \__ \ | |  | |_| | | | | \__ \ |_| | (_| | (_) |
#   \___/ \__,_|_|    \_/ |_|___/ |_|   \__,_|_| |_| |___/\__,_|\__,_|\___/
#
#                                __      __
#   _ __ _ __ ___          _ __ / _|    / /
#  | '__| '_ ` _ \   _____| '__| |_    / /
#  | |  | | | | | | |_____| |  |  _|  / /
#  |_|  |_| |_| |_|       |_|  |_|   /_/
#

### Portals ###
exec_always sleep 3 && systemctl --user restart xdg-desktop-portal-wlr xdg-desktop-portal-gtk xdg-desktop-portal
#exec_always systemctl --user restart xdg-desktop-portal-wlr
#exec_always systemctl --user restart xdg-desktop-portal-gtk

# polkit
exec lxpolkit

### Waybar ###
exec waybar

### Swaybg ###
exec_always swaybg -i ~/Pictures/Fondos\ de\ pantalla/"Firewatch-Rainy_1920x1080.jpg" -m fill

### Swayidle ###

# To use `suspend-then-hibernate` 
# you must have a swap partition or swapfile
# depending on your case one of them is more useful 
# and the amount of space also depends on your needs
# you may also need to configure grub or your bootloader

exec swayidle -w \
    timeout 600 'gtklock -d' \
    timeout 900 'swaymsg "output * dpms off"' \
	resume 'swaymsg "output * dpms on"' \
    timeout 1200 'systemctl suspend-then-hibernate' \
    before-sleep 'pgrep gtklock ||  gtklock' 

# What's done?
# This will lock your screen after 600s of inactivity (10min)
# then turn off your displays after another 300s (15min), 
# then suspend your device after 300s more (20min)
# and wait for 300s more to hibernate (25min)
# finally turn your screens back on when resumed 
# It will also lock your screen before your computer goes to sleep.
# I recommend read `man 5 systemd-sleep.conf` to more info about
# suspend-then-hibernate and configs

### Icon Theme, Cursor & Font ###

exec_always {
    swaymsg font "$font_name"
    swaymsg seat seat0 xcursor_theme "$cursor_theme" "$cursor_size"
    gsettings set org.gnome.desktop.interface font-name "$font_name"
    gsettings set org.gnome.desktop.interface icon-theme "$icon_theme"
    gsettings set org.gnome.desktop.interface cursor-theme "$cursor_theme"
    gsettings set org.gnome.desktop.interface cursor-size "$cursor_size"
}

# When reloading Sway, read the variables and apply it to the environment
# (you can find the variables in 10-variables.conf)
# I recommend install `nwg-look` and using the
# 10-variables.conf & 40-autostart.conf config
# it makes changing themes, cursor and font  easier
# even it's not perfect and sometimes you have to reboot or
# restart your sway session
